/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cinev;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author fband
 */
public class InterfazInSesion extends javax.swing.JFrame {
    
  int xMouse, yMouse;
  private String rutaImagen; 
  private Conexion conexion = new Conexion();
    Connection con = conexion.establecerConexion();
    
    /**
     * Creates new form InterfazRegPeli
     */
    public InterfazInSesion() {
        initComponents();
        this.setLocationRelativeTo(this);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        prece = new javax.swing.JPanel();
        guardar = new javax.swing.JPanel();
        cerrarlbl = new javax.swing.JLabel();
        tituloCine = new javax.swing.JLabel();
        tituloCine1 = new javax.swing.JLabel();
        inicioBtn = new javax.swing.JToggleButton();
        tituloCine2 = new javax.swing.JLabel();
        iniPanel = new javax.swing.JPanel();
        usuarioText = new javax.swing.JTextField();
        passPanel = new javax.swing.JPanel();
        passText = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(11, 23, 128));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(13, 20, 58));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prece.setBackground(new java.awt.Color(13, 20, 58));
        prece.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                preceMouseDragged(evt);
            }
        });
        prece.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                preceMousePressed(evt);
            }
        });

        guardar.setBackground(new java.awt.Color(102, 0, 102));
        guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                guardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                guardarMouseExited(evt);
            }
        });

        cerrarlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cerrarlbl.setForeground(new java.awt.Color(255, 255, 255));
        cerrarlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrarlbl.setText("x");

        javax.swing.GroupLayout guardarLayout = new javax.swing.GroupLayout(guardar);
        guardar.setLayout(guardarLayout);
        guardarLayout.setHorizontalGroup(
            guardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guardarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cerrarlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        guardarLayout.setVerticalGroup(
            guardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guardarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrarlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout preceLayout = new javax.swing.GroupLayout(prece);
        prece.setLayout(preceLayout);
        preceLayout.setHorizontalGroup(
            preceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, preceLayout.createSequentialGroup()
                .addGap(0, 591, Short.MAX_VALUE)
                .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        preceLayout.setVerticalGroup(
            preceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(preceLayout.createSequentialGroup()
                .addComponent(guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg.add(prece, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, -1));

        tituloCine.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloCine.setForeground(new java.awt.Color(255, 255, 255));
        tituloCine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloCine.setText("Contraseña:");
        bg.add(tituloCine, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 150, 50));

        tituloCine1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tituloCine1.setForeground(new java.awt.Color(255, 255, 255));
        tituloCine1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloCine1.setText("Cine Vortex ");
        tituloCine1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        bg.add(tituloCine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 260, 50));

        inicioBtn.setBackground(new java.awt.Color(0, 0, 255));
        inicioBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        inicioBtn.setForeground(new java.awt.Color(255, 255, 255));
        inicioBtn.setText("Iniciar Sesion ");
        inicioBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inicioBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inicioBtnMouseExited(evt);
            }
        });
        inicioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioBtnActionPerformed(evt);
            }
        });
        bg.add(inicioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 200, 60));

        tituloCine2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloCine2.setForeground(new java.awt.Color(255, 255, 255));
        tituloCine2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloCine2.setText("Loggin:");
        bg.add(tituloCine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 110, 50));

        iniPanel.setBackground(new java.awt.Color(102, 0, 102));

        usuarioText.setBackground(new java.awt.Color(102, 0, 102));
        usuarioText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usuarioText.setForeground(java.awt.Color.gray);
        usuarioText.setText("Ingrese su usuario");
        usuarioText.setBorder(null);
        usuarioText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usuarioTextMousePressed(evt);
            }
        });
        usuarioText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout iniPanelLayout = new javax.swing.GroupLayout(iniPanel);
        iniPanel.setLayout(iniPanelLayout);
        iniPanelLayout.setHorizontalGroup(
            iniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iniPanelLayout.createSequentialGroup()
                .addComponent(usuarioText, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        iniPanelLayout.setVerticalGroup(
            iniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iniPanelLayout.createSequentialGroup()
                .addComponent(usuarioText, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg.add(iniPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 300, 40));

        passPanel.setBackground(new java.awt.Color(102, 0, 102));

        passText.setBackground(new java.awt.Color(102, 0, 102));
        passText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passText.setForeground(java.awt.Color.gray);
        passText.setText("*********");
        passText.setBorder(null);
        passText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passTextMousePressed(evt);
            }
        });
        passText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout passPanelLayout = new javax.swing.GroupLayout(passPanel);
        passPanel.setLayout(passPanelLayout);
        passPanelLayout.setHorizontalGroup(
            passPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passPanelLayout.createSequentialGroup()
                .addComponent(passText, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        passPanelLayout.setVerticalGroup(
            passPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passPanelLayout.createSequentialGroup()
                .addComponent(passText, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg.add(passPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 300, 40));

        jPanel1.setBackground(new java.awt.Color(13, 20, 58));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 40, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseEntered
       guardar.setBackground(Color.red);
    }//GEN-LAST:event_guardarMouseEntered

    private void guardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseExited
        guardar.setBackground(new Color(102,0,102));
    }//GEN-LAST:event_guardarMouseExited

    private void preceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preceMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_preceMousePressed

    private void preceMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preceMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_preceMouseDragged

    private void guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseClicked

        System.exit(0);    }//GEN-LAST:event_guardarMouseClicked

    private void inicioBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioBtnMouseEntered
        inicioBtn.setBackground(Color.GREEN);
    }//GEN-LAST:event_inicioBtnMouseEntered

    private void inicioBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioBtnMouseExited
      
        inicioBtn.setBackground(new Color(102,0,102));
    }//GEN-LAST:event_inicioBtnMouseExited

    private void inicioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioBtnActionPerformed
        verificarCredenciales();
    }//GEN-LAST:event_inicioBtnActionPerformed

    private void verificarCredenciales() {
        // Obtener los valores de los JTextField
        String usuario = usuarioText.getText().trim();
        String contrasena = new String(passText.getPassword()).trim(); // Convertir char[] a String

        // Validar que los campos no estén vacíos
        if (usuario.isEmpty() || contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese usuario y contraseña.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Consulta SQL para verificar credenciales y cargo
        String sql = "SELECT id_empleado FROM empleado WHERE usuario = ? AND contrasena = ? AND cargo = 'Cajero'";

        try (PreparedStatement pst = con.prepareStatement(sql)) {
            pst.setString(1, usuario);
            pst.setString(2, contrasena);

            try (ResultSet rs = pst.executeQuery()) {
                if (rs.next()) { // Si hay un resultado, las credenciales son correctas
                    JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                    // Cerrar la ventana actual
                    this.dispose();

                    // Abrir la interfaz de ventas
                    new InterfazVenta(usuarioText.getText()).setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Credenciales incorrectas o no tienes permisos de cajero.", "Acceso denegado", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error en la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    
    private void passTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTextActionPerformed

    private void usuarioTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioTextActionPerformed

    private void usuarioTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioTextMousePressed
        if(usuarioText.getText().equals("Ingrese su usuario")){
            usuarioText.setText("");
            usuarioText.setForeground(Color.white);
        }
        if(passText.getText().isEmpty()){
            passText.setText("*********");
            passText.setForeground(Color.gray);
        }
    }//GEN-LAST:event_usuarioTextMousePressed

    private void passTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTextMousePressed
         if(passText.getText().equals("*********")){
            passText.setText("");
            passText.setForeground(Color.white);
        }
        if(usuarioText.getText().isEmpty()){
            usuarioText.setText("Ingrese su usuario");
            usuarioText.setForeground(Color.gray);
        }
    }//GEN-LAST:event_passTextMousePressed

    
    
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazInSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazInSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazInSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazInSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazInSesion().setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel cerrarlbl;
    private javax.swing.JPanel guardar;
    private javax.swing.JPanel iniPanel;
    private javax.swing.JToggleButton inicioBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel passPanel;
    private javax.swing.JPasswordField passText;
    private javax.swing.JPanel prece;
    private javax.swing.JLabel tituloCine;
    private javax.swing.JLabel tituloCine1;
    private javax.swing.JLabel tituloCine2;
    private javax.swing.JTextField usuarioText;
    // End of variables declaration//GEN-END:variables
}
