/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cinev;

import java.awt.Color;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author fband
 */
public class InterfazAcTPelis extends javax.swing.JFrame {
    
  int xMouse, yMouse;
  private String rutaImagen; 
  private Conexion conexion = new Conexion();
    Connection con = conexion.establecerConexion();
    
    /**
     * Creates new form InterfazRegPeli
     */
    public InterfazAcTPelis() {
        initComponents();
        this.setLocationRelativeTo(this);
        SetImageLabel(menulbl,"src/main/java/images/Menu75.png");
        SetImageLabel(candylbl,"src/main/java/images/Store 75.png");
        SetImageLabel(ticlbl,"src/main/java/images/Ticket75.png");
        SetImageLabel(usulbl,"src/main/java/images/User75.png");
        SetImageLabel(whatsalbl,"src/main/java/images/Whats75.png");
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        menuF = new javax.swing.JPanel();
        menulbl = new javax.swing.JLabel();
        ticF = new javax.swing.JPanel();
        ticlbl = new javax.swing.JLabel();
        candyF = new javax.swing.JPanel();
        candylbl = new javax.swing.JLabel();
        usuF = new javax.swing.JPanel();
        usulbl = new javax.swing.JLabel();
        whatsaF = new javax.swing.JPanel();
        whatsalbl = new javax.swing.JLabel();
        prece = new javax.swing.JPanel();
        guardar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        duracionPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        duracion = new javax.swing.JTextField();
        fechaPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        fechaEs = new javax.swing.JTextField();
        generoPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        genero = new javax.swing.JTextField();
        tituloPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        clasifPanel = new javax.swing.JPanel();
        clasifLbl = new javax.swing.JLabel();
        clasif = new javax.swing.JTextField();
        paraFoto = new javax.swing.JLabel();
        tituloACtLB = new javax.swing.JLabel();
        cancelarBtn = new javax.swing.JToggleButton();
        actualizarBtn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(11, 23, 128));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(13, 20, 58));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(17, 27, 82));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuF.setBackground(new java.awt.Color(17, 27, 82));
        menuF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuFMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuFMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuFMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menuFLayout = new javax.swing.GroupLayout(menuF);
        menuF.setLayout(menuFLayout);
        menuFLayout.setHorizontalGroup(
            menuFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuFLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(menulbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        menuFLayout.setVerticalGroup(
            menuFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuFLayout.createSequentialGroup()
                .addComponent(menulbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menu.add(menuF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, 70));

        ticF.setBackground(new java.awt.Color(17, 27, 82));
        ticF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ticF.setPreferredSize(new java.awt.Dimension(70, 70));
        ticF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ticFMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ticFMouseExited(evt);
            }
        });

        ticlbl.setPreferredSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout ticFLayout = new javax.swing.GroupLayout(ticF);
        ticF.setLayout(ticFLayout);
        ticFLayout.setHorizontalGroup(
            ticFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(ticFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ticFLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ticlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        ticFLayout.setVerticalGroup(
            ticFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(ticFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ticFLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ticlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        menu.add(ticF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, 70));

        candyF.setBackground(new java.awt.Color(17, 27, 82));
        candyF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        candyF.setPreferredSize(new java.awt.Dimension(70, 70));
        candyF.setRequestFocusEnabled(false);
        candyF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                candyFMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                candyFMouseExited(evt);
            }
        });

        javax.swing.GroupLayout candyFLayout = new javax.swing.GroupLayout(candyF);
        candyF.setLayout(candyFLayout);
        candyFLayout.setHorizontalGroup(
            candyFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(candyFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(candyFLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(candylbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        candyFLayout.setVerticalGroup(
            candyFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(candyFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(candyFLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(candylbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        menu.add(candyF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        usuF.setBackground(new java.awt.Color(17, 27, 82));
        usuF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usuF.setPreferredSize(new java.awt.Dimension(70, 70));
        usuF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usuFMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usuFMouseExited(evt);
            }
        });

        javax.swing.GroupLayout usuFLayout = new javax.swing.GroupLayout(usuF);
        usuF.setLayout(usuFLayout);
        usuFLayout.setHorizontalGroup(
            usuFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usuFLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(usulbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        usuFLayout.setVerticalGroup(
            usuFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usuFLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(usulbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menu.add(usuF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 70, 70));

        whatsaF.setBackground(new java.awt.Color(17, 27, 82));
        whatsaF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        whatsaF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                whatsaFMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                whatsaFMouseExited(evt);
            }
        });

        javax.swing.GroupLayout whatsaFLayout = new javax.swing.GroupLayout(whatsaF);
        whatsaF.setLayout(whatsaFLayout);
        whatsaFLayout.setHorizontalGroup(
            whatsaFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(whatsalbl, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        whatsaFLayout.setVerticalGroup(
            whatsaFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(whatsalbl, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        menu.add(whatsaF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 70, 70));

        bg.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 500));

        prece.setBackground(new java.awt.Color(13, 20, 58));
        prece.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                preceMouseDragged(evt);
            }
        });
        prece.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                preceMousePressed(evt);
            }
        });

        guardar.setBackground(new java.awt.Color(102, 0, 102));
        guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                guardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                guardarMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("x");

        javax.swing.GroupLayout guardarLayout = new javax.swing.GroupLayout(guardar);
        guardar.setLayout(guardarLayout);
        guardarLayout.setHorizontalGroup(
            guardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guardarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        guardarLayout.setVerticalGroup(
            guardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guardarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout preceLayout = new javax.swing.GroupLayout(prece);
        prece.setLayout(preceLayout);
        preceLayout.setHorizontalGroup(
            preceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, preceLayout.createSequentialGroup()
                .addGap(0, 691, Short.MAX_VALUE)
                .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        preceLayout.setVerticalGroup(
            preceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(preceLayout.createSequentialGroup()
                .addComponent(guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg.add(prece, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 730, -1));

        duracionPanel.setBackground(new java.awt.Color(102, 0, 102));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Duracion:");

        duracion.setBackground(new java.awt.Color(102, 0, 102));
        duracion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        duracion.setForeground(java.awt.Color.gray);
        duracion.setText("130 (minutos)");
        duracion.setBorder(null);
        duracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                duracionMousePressed(evt);
            }
        });

        javax.swing.GroupLayout duracionPanelLayout = new javax.swing.GroupLayout(duracionPanel);
        duracionPanel.setLayout(duracionPanelLayout);
        duracionPanelLayout.setHorizontalGroup(
            duracionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(duracionPanelLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(duracion, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE))
        );
        duracionPanelLayout.setVerticalGroup(
            duracionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addGroup(duracionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(duracion)
                .addContainerGap())
        );

        bg.add(duracionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, 40));

        fechaPanel.setBackground(new java.awt.Color(102, 0, 102));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fecha de estreno:");

        fechaEs.setBackground(new java.awt.Color(102, 0, 102));
        fechaEs.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fechaEs.setForeground(java.awt.Color.gray);
        fechaEs.setText("AAAA-MM-DD");
        fechaEs.setBorder(null);
        fechaEs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fechaEsMousePressed(evt);
            }
        });

        javax.swing.GroupLayout fechaPanelLayout = new javax.swing.GroupLayout(fechaPanel);
        fechaPanel.setLayout(fechaPanelLayout);
        fechaPanelLayout.setHorizontalGroup(
            fechaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fechaPanelLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaEs, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
        );
        fechaPanelLayout.setVerticalGroup(
            fechaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(fechaEs)
        );

        bg.add(fechaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));

        generoPanel.setBackground(new java.awt.Color(102, 0, 102));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Genero:");

        genero.setBackground(new java.awt.Color(102, 0, 102));
        genero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        genero.setForeground(java.awt.Color.gray);
        genero.setText("Accion");
        genero.setBorder(null);
        genero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                generoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout generoPanelLayout = new javax.swing.GroupLayout(generoPanel);
        generoPanel.setLayout(generoPanelLayout);
        generoPanelLayout.setHorizontalGroup(
            generoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generoPanelLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genero, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))
        );
        generoPanelLayout.setVerticalGroup(
            generoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(genero)
        );

        bg.add(generoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        tituloPanel.setBackground(new java.awt.Color(102, 0, 102));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TItulo:");

        titulo.setBackground(new java.awt.Color(102, 0, 102));
        titulo.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        titulo.setForeground(java.awt.Color.gray);
        titulo.setText("Matrix 2: Recargado");
        titulo.setBorder(null);
        titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tituloMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tituloMousePressed(evt);
            }
        });
        titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tituloPanelLayout = new javax.swing.GroupLayout(tituloPanel);
        tituloPanel.setLayout(tituloPanelLayout);
        tituloPanelLayout.setHorizontalGroup(
            tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloPanelLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))
        );
        tituloPanelLayout.setVerticalGroup(
            tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloPanelLayout.createSequentialGroup()
                .addGroup(tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(titulo)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(tituloPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 410, 40));

        clasifPanel.setBackground(new java.awt.Color(102, 0, 102));

        clasifLbl.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        clasifLbl.setForeground(new java.awt.Color(255, 255, 255));
        clasifLbl.setText("Clasificación:");

        clasif.setBackground(new java.awt.Color(102, 0, 102));
        clasif.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clasif.setForeground(java.awt.Color.gray);
        clasif.setText("R");
        clasif.setBorder(null);
        clasif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clasifMousePressed(evt);
            }
        });

        javax.swing.GroupLayout clasifPanelLayout = new javax.swing.GroupLayout(clasifPanel);
        clasifPanel.setLayout(clasifPanelLayout);
        clasifPanelLayout.setHorizontalGroup(
            clasifPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clasifPanelLayout.createSequentialGroup()
                .addComponent(clasifLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clasif, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        clasifPanelLayout.setVerticalGroup(
            clasifPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clasifLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(clasif)
        );

        bg.add(clasifPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, -1));

        paraFoto.setBackground(new java.awt.Color(255, 255, 255));
        paraFoto.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        paraFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paraFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paraFotoMouseClicked(evt);
            }
        });
        bg.add(paraFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 240, 290));

        tituloACtLB.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloACtLB.setForeground(new java.awt.Color(255, 255, 255));
        tituloACtLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloACtLB.setText("Actualizar de Pelicula");
        bg.add(tituloACtLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 390, 40));

        cancelarBtn.setBackground(new java.awt.Color(102, 0, 102));
        cancelarBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        cancelarBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelarBtn.setText("CANCELAR");
        cancelarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelarBtnMouseExited(evt);
            }
        });
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });
        bg.add(cancelarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 180, 60));

        actualizarBtn.setBackground(new java.awt.Color(102, 0, 102));
        actualizarBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        actualizarBtn.setForeground(new java.awt.Color(255, 255, 255));
        actualizarBtn.setText("ACTUALIZAR");
        actualizarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                actualizarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                actualizarBtnMouseExited(evt);
            }
        });
        bg.add(actualizarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 180, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloActionPerformed

    private void tituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloMouseClicked

    private void tituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloMousePressed
        if(titulo.getText().equals("Matrix 2: Recargado")){
        titulo.setText("");
       titulo.setForeground(Color.white);
       }
       if(duracion.getText().isEmpty()){
           duracion.setText("130 (minutos)");
           duracion.setForeground(Color.gray);
       }
       if(fechaEs.getText().isEmpty()){
           fechaEs.setText("AAAA-MM-DD");
           fechaEs.setForeground(Color.gray);
       }
       if(genero.getText().isEmpty()){
           genero.setText("Accion");
           genero.setForeground(Color.gray);
       }
       if(clasif.getText().isEmpty()){
           clasif.setText("R");
           clasif.setForeground(Color.gray);
       }
    }//GEN-LAST:event_tituloMousePressed

    private void duracionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duracionMousePressed
       if(duracion.getText().equals("130 (minutos)")){
             duracion.setText("");
       duracion.setForeground(Color.white);
        }
        if(fechaEs.getText().isEmpty()){
           fechaEs.setText("AAAA-MM-DD");
           fechaEs.setForeground(Color.gray);
       }
       if(genero.getText().isEmpty()){
           genero.setText("Accion");
           genero.setForeground(Color.gray);
       }
       if(clasif.getText().isEmpty()){
           clasif.setText("R");
           clasif.setForeground(Color.gray);
       }
       if(titulo.getText().isEmpty()){
           titulo.setText("Matrix 2: Recargado");
           titulo.setForeground(Color.gray);
       }
    }//GEN-LAST:event_duracionMousePressed

    private void fechaEsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaEsMousePressed
           
        if(fechaEs.getText().equals("AAAA-MM-DD")){
           fechaEs.setText("");
       fechaEs.setForeground(Color.white);
       }
        if(genero.getText().isEmpty()){
           genero.setText("Accion");
           genero.setForeground(Color.gray);
       }
       if(clasif.getText().isEmpty()){
           clasif.setText("R");
           clasif.setForeground(Color.gray);
       }
        if(titulo.getText().isEmpty()){
           titulo.setText("Matrix 2: Recargado");
           titulo.setForeground(Color.gray);
       }
        if(duracion.getText().isEmpty()){
           duracion.setText("130 (minutos)");
           duracion.setForeground(Color.gray);
       }
    }//GEN-LAST:event_fechaEsMousePressed

    private void generoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generoMousePressed
        if(genero.getText().equals("Accion")){
           genero.setText("");
       genero.setForeground(Color.white);
       }
        if(fechaEs.getText().isEmpty()){
           fechaEs.setText("AAAA-MM-DD");
           fechaEs.setForeground(Color.gray);
       }
       if(clasif.getText().isEmpty()){
           clasif.setText("R");
           clasif.setForeground(Color.gray);
       }
        if(titulo.getText().isEmpty()){
           titulo.setText("Matrix 2: Recargado");
           titulo.setForeground(Color.gray);
       }
        if(duracion.getText().isEmpty()){
           duracion.setText("130 (minutos)");
           duracion.setForeground(Color.gray);
       }
    }//GEN-LAST:event_generoMousePressed

    private void clasifMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clasifMousePressed
         if(clasif.getText().equals("R")){
           clasif.setText("");
       clasif.setForeground(Color.white);
       }
        if(fechaEs.getText().isEmpty()){
           fechaEs.setText("AAAA-MM-DD");
           fechaEs.setForeground(Color.gray);
       }
       
       if(genero.getText().isEmpty()){
           genero.setText("Accion");
           genero.setForeground(Color.gray);
       }
        if(titulo.getText().isEmpty()){
           titulo.setText("Matrix 2: Recargado");
           titulo.setForeground(Color.gray);
       }
        if(duracion.getText().isEmpty()){
           duracion.setText("130 (minutos)");
           duracion.setForeground(Color.gray);
       }
    }//GEN-LAST:event_clasifMousePressed

    private void guardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseEntered
       guardar.setBackground(Color.red);
    }//GEN-LAST:event_guardarMouseEntered

    private void guardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseExited
        guardar.setBackground(new Color(102,0,102));
    }//GEN-LAST:event_guardarMouseExited

    private void preceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preceMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_preceMousePressed

    private void preceMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preceMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_preceMouseDragged

    private void guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseClicked

        System.exit(0);    }//GEN-LAST:event_guardarMouseClicked

    private void paraFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paraFotoMouseClicked
        buscarImagen();
    }//GEN-LAST:event_paraFotoMouseClicked

    private void menuFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFMouseEntered
        menuF.setBackground(new Color(153,153,255));
    }//GEN-LAST:event_menuFMouseEntered

    private void menuFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFMouseExited
       menuF.setBackground(new Color(17,27,82));
    }//GEN-LAST:event_menuFMouseExited

    private void ticFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticFMouseEntered
        ticF.setBackground(new Color(153,153,255)); 
    }//GEN-LAST:event_ticFMouseEntered

    private void ticFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticFMouseExited
       ticF.setBackground(new Color(17,27,82));
    }//GEN-LAST:event_ticFMouseExited

    private void candyFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_candyFMouseEntered
        candyF.setBackground(new Color(153,153,255)); 
    }//GEN-LAST:event_candyFMouseEntered

    private void candyFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_candyFMouseExited
        candyF.setBackground(new Color(17,27,82));
    }//GEN-LAST:event_candyFMouseExited

    private void usuFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuFMouseEntered
        usuF.setBackground(new Color(153,153,255)); 

    }//GEN-LAST:event_usuFMouseEntered

    private void usuFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuFMouseExited
       usuF.setBackground(new Color(17,27,82)); 
    }//GEN-LAST:event_usuFMouseExited

    private void whatsaFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_whatsaFMouseEntered
        whatsaF.setBackground(new Color(153,153,255)); 
    }//GEN-LAST:event_whatsaFMouseEntered

    private void whatsaFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_whatsaFMouseExited
         whatsaF.setBackground(new Color(17,27,82)); 
    }//GEN-LAST:event_whatsaFMouseExited

    private void actualizarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizarBtnMouseEntered
        actualizarBtn.setBackground(Color.blue);
    }//GEN-LAST:event_actualizarBtnMouseEntered

    private void actualizarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizarBtnMouseExited
        actualizarBtn.setBackground(new Color(17,27,82));
    }//GEN-LAST:event_actualizarBtnMouseExited

    private void cancelarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarBtnMouseEntered
        cancelarBtn.setBackground(Color.red);
    }//GEN-LAST:event_cancelarBtnMouseEntered

    private void cancelarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarBtnMouseExited
       cancelarBtn.setBackground(new Color(17,27,82));
    }//GEN-LAST:event_cancelarBtnMouseExited

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
      java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGestionPelis().setVisible(true);
            }
        });
      this.setVisible(false);
    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void menuFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFMouseClicked
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazAdmin().setVisible(true);
            }
        });
      this.setVisible(false);
    }//GEN-LAST:event_menuFMouseClicked

      public static boolean esTextoNumerico(String texto) {
        // Si el texto es nulo o está vacío, no es numérico.
        if (texto == null || texto.equals("")) {
            return false;
        }

        // Recorremos cada carácter del texto.
        for (int i = 0; i < texto.length(); i++) {
            char c = texto.charAt(i); // Obtenemos el carácter en la posición actual.
            if (c < '0' || c > '9') { // Verificamos si no es un número.
                return false; // Si no es un número, devolvemos false.
            }
        }

        // Si todos los caracteres son números, devolvemos true.
        return true;
    }
      private void buscarImagen() {
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Imagenes (JPG, PNG, GIF)", "jpg", "png", "gif");
        fileChooser.setFileFilter(filter);

        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            rutaImagen = file.getAbsolutePath();
            ImageIcon icon = new ImageIcon(new ImageIcon(rutaImagen).getImage().getScaledInstance(paraFoto.getWidth(), paraFoto.getHeight(), Image.SCALE_SMOOTH));
            paraFoto.setIcon(icon);
        }
    }
private void guardarEnBD() {
        String nombre = titulo.getText().trim();
        String fechaEstreno = fechaEs.getText().trim();
        String genero1 = genero.getText().trim();
        String duracion1 = duracion.getText().trim();
        String clasificacion = clasif.getText().trim();

        if (paraFoto.getIcon() == null|| nombre.isEmpty() || fechaEstreno.isEmpty() || genero1.isEmpty() || duracion1.isEmpty() || clasificacion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos y selecciona una imagen.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Validar formato de fecha
            java.sql.Date sqlFechaEstreno;
            try {
                sqlFechaEstreno = java.sql.Date.valueOf(fechaEstreno);
            } catch (IllegalArgumentException e) {
                JOptionPane.showMessageDialog(this, "El formato de la fecha debe ser YYYY-MM-DD.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Validar duración como entero
            int duracionInt;
            try {
                duracionInt = Integer.parseInt(duracion1);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "La duración debe ser un número entero.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Validar que la imagen exista
            File imagenFile = new File(rutaImagen);
            if (!imagenFile.exists()) {
                JOptionPane.showMessageDialog(this, "La imagen seleccionada no existe.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Leer la imagen como un InputStream
            InputStream is = new FileInputStream(imagenFile);

            // Consulta SQL para insertar los datos
            String sql = "INSERT INTO pelicula (nombre_pelicula, fecha_estreno, genero, duracion, clasificacion, imagen) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement ps = con.prepareStatement(sql);

            // Asignar valores a la consulta
            ps.setString(1, nombre);
            ps.setDate(2, sqlFechaEstreno);
            ps.setString(3, genero1);
            ps.setInt(4, duracionInt);
            ps.setString(5, clasificacion);
            ps.setBinaryStream(6, is, (int) imagenFile.length()); // Ahora el InputStream no se cierra prematuramente

            // Ejecutar la consulta
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Película guardada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            // Cerrar recursos
            ps.close();
            is.close();

         

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al guardar en la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazAcTPelis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazAcTPelis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazAcTPelis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazAcTPelis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazAcTPelis().setVisible(true);
            }
        });
    }
    private void SetImageLabel(JLabel labelName, String root){
        
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton actualizarBtn;
    private javax.swing.JPanel bg;
    private javax.swing.JToggleButton cancelarBtn;
    private javax.swing.JPanel candyF;
    private javax.swing.JLabel candylbl;
    private javax.swing.JTextField clasif;
    private javax.swing.JLabel clasifLbl;
    private javax.swing.JPanel clasifPanel;
    private javax.swing.JTextField duracion;
    private javax.swing.JPanel duracionPanel;
    private javax.swing.JTextField fechaEs;
    private javax.swing.JPanel fechaPanel;
    private javax.swing.JTextField genero;
    private javax.swing.JPanel generoPanel;
    private javax.swing.JPanel guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuF;
    private javax.swing.JLabel menulbl;
    private javax.swing.JLabel paraFoto;
    private javax.swing.JPanel prece;
    private javax.swing.JPanel ticF;
    private javax.swing.JLabel ticlbl;
    private javax.swing.JTextField titulo;
    private javax.swing.JLabel tituloACtLB;
    private javax.swing.JPanel tituloPanel;
    private javax.swing.JPanel usuF;
    private javax.swing.JLabel usulbl;
    private javax.swing.JPanel whatsaF;
    private javax.swing.JLabel whatsalbl;
    // End of variables declaration//GEN-END:variables
}
